interface BusinessTerm {
  summary: string;
  category: 'finance' | 'metrics' | 'accounting' | 'strategy' | 'marketing' | 'operations' | 'innovation' | 'entrepreneurship';
  synonyms?: string[];
  relatedTerms?: string[];
  details: string[];
}

export const businessTerms: Record<string, BusinessTerm> = {
  'how to start a business': {
    summary: '🎯 Quick guide to launching your first business venture.',
    category: 'entrepreneurship',
    details: [
      '📝 Summary',
      'A step-by-step process to transform your idea into a functioning business.',
      '',
      '📦 Phase 1: Planning',
      'Market Research • Study your target customers',
      'Business Plan • Write your roadmap',
      'Funding Needs • Calculate startup costs',
      '',
      '💼 Phase 2: Legal Setup',
      'Business Structure • Choose LLC or corporation',
      'Registration • Get permits and licenses',
      'Bank Account • Separate business finances',
      '',
      '📈 Phase 3: Launch Prep',
      'Brand Identity • Create logo and website',
      'Operations • Set up tools and systems',
      'Team • Hire key people if needed',
      '',
      '🚀 Phase 4: Market Entry',
      'Marketing Plan • Start promoting',
      'Sales Process • Begin customer outreach',
      'Feedback Loop • Gather early responses',
      '',
      '💡 Bottom Line',
      'Start small, test quickly, and adjust based on real customer feedback.'
    ]
  },
  'business': {
    summary: '💼 A business is an organization or entity engaged in commercial, industrial, or professional activities with the goal of earning profit or achieving a specific mission.',
    category: 'strategy',
    details: [
      'Core Components • Provides value through products/services, serves customers, operates with systems, aims for sustainability',
      'Value Creation • Solves problems or fulfills needs in exchange for money, time, or resources',
      'Customer Focus • Serves individuals, other businesses (B2B), or institutions',
      'Operations • Includes management, finance, marketing, operations, and sales systems',
      'Business Models • Can be for-profit (like Apple), nonprofit (like Red Cross), or hybrid',
      'Legal Structures • Options include sole proprietorship, partnership, corporation, and LLC',
      'Success Metrics • Measures both financial profit and mission impact',
      '',
      '💡 Bottom line: A business is how people organize themselves to create value and serve others in a sustainable way.'
    ]
  },
  'swot analysis': {
    summary: '📋 A strategic planning tool that helps evaluate your business position by analyzing internal and external factors.',
    category: 'strategy',
    synonyms: ['swot', 'strategic analysis'],
    relatedTerms: ['strategic planning', 'competitive analysis', 'business model canvas'],
    details: [
      '📝 Summary',
      'SWOT helps you make better decisions by understanding your position in the market through a structured analysis framework.',
      '',
      '💪 Internal Factors',
      'Strengths • What you do well',
      'Weaknesses • Where you struggle',
      '',
      '🌍 External Factors',
      'Opportunities • Potential advantages',
      'Threats • Potential risks',
      '',
      '📊 Action Items',
      'Strategy • Use strengths to capture opportunities',
      'Defense • Fix weaknesses before threats hit',
      'Timing • Review and update quarterly',
      '',
      '💡 Bottom Line',
      'SWOT turns complex business situations into clear, actionable strategies.'
    ]
  },
  'marketing mix': {
    summary: 'The Marketing Mix (4 Ps) is a framework used to define a marketing strategy through Product, Price, Place, and Promotion.',
    category: 'marketing',
    synonyms: ['4 ps', 'four ps', 'marketing 4ps'],
    relatedTerms: ['market segmentation', 'branding', 'marketing strategy'],
    details: [
      'The 4 Ps consist of:',
      '  - Product: What you sell',
      '    * Features and benefits',
      '    * Quality and design',
      '    * Branding and packaging',
      '  - Price: How much you charge',
      '    * Pricing strategy',
      '    * Discounts and promotions',
      '    * Payment terms',
      '  - Place: Where you sell',
      '    * Distribution channels',
      '    * Market coverage',
      '    * Inventory management',
      '  - Promotion: How you communicate',
      '    * Advertising',
      '    * Public relations',
      '    * Sales promotion',
      'Modern additions (7 Ps):',
      '  - People: Staff and customer service',
      '  - Process: Service delivery',
      '  - Physical Evidence: Tangible elements'
    ]
  },
  'porters five forces': {
    summary: "Porter's Five Forces is a framework for analyzing competition and industry attractiveness.",
    category: 'strategy',
    synonyms: ['five forces model', 'porter model', 'industry analysis'],
    relatedTerms: ['competitive advantage', 'market analysis', 'strategic planning'],
    details: [
      'The five forces are:',
      '  - Competitive Rivalry',
      '    * Number of competitors',
      '    * Industry growth rate',
      '    * Product differentiation',
      '  - Threat of New Entrants',
      '    * Entry barriers',
      '    * Capital requirements',
      '    * Economies of scale',
      '  - Threat of Substitutes',
      '    * Switching costs',
      '    * Price-performance trade-off',
      '    * Buyer propensity to substitute',
      '  - Bargaining Power of Buyers',
      '    * Buyer concentration',
      '    * Product differentiation',
      '    * Price sensitivity',
      '  - Bargaining Power of Suppliers',
      '    * Supplier concentration',
      '    * Switching costs',
      '    * Input differentiation'
    ]
  },
  'value chain': {
    summary: 'Value Chain Analysis examines activities that add value to products/services from conception to delivery.',
    category: 'strategy',
    synonyms: ['value chain analysis', 'supply chain value'],
    relatedTerms: ['supply chain management', 'competitive advantage', 'operational efficiency'],
    details: [
      'Primary Activities:',
      '  - Inbound Logistics: Receiving and storing materials',
      '  - Operations: Converting inputs into outputs',
      '  - Outbound Logistics: Delivering products',
      '  - Marketing & Sales: Reaching customers',
      '  - Service: Post-sale support',
      'Support Activities:',
      '  - Infrastructure: Management and planning',
      '  - HR Management: Recruiting and training',
      '  - Technology Development: R&D and automation',
      '  - Procurement: Purchasing inputs',
      'Used to:',
      '  - Identify competitive advantages',
      '  - Improve efficiency',
      '  - Reduce costs',
      '  - Enhance differentiation'
    ]
  },
  'profit margin': {
    summary: 'Profit margin is the percentage of revenue that represents profit after all expenses are deducted.',
    category: 'finance',
    synonyms: ['margin', 'profit percentage', 'markup'],
    relatedTerms: ['gross margin', 'net margin', 'operating margin'],
    details: [
      'Profit margin shows how much of each dollar in revenue becomes profit',
      'Types of profit margins:',
      '  - Gross margin: Revenue minus cost of goods sold',
      '  - Operating margin: Profit from operations before interest and taxes',
      '  - Net margin: Final profit after all expenses',
      'To calculate:',
      '  - Gross Margin = (Revenue - COGS) / Revenue × 100',
      '  - Net Margin = Net Income / Revenue × 100',
      'Higher margins indicate:',
      '  - Better pricing power',
      '  - Operational efficiency',
      '  - Competitive advantage'
    ]
  },
  'runway': {
    summary: 'Runway is the amount of time a company can continue operating with its current cash reserves at the current burn rate.',
    category: 'finance',
    synonyms: ['cash runway', 'financial runway'],
    relatedTerms: ['burn rate', 'cash flow', 'working capital'],
    details: [
      'Runway is calculated by dividing total cash by monthly burn rate',
      'Key considerations:',
      '  - Longer runway provides more time to reach profitability',
      '  - Typical startup aims for 12-18 months of runway',
      '  - Shorter runway may require immediate fundraising',
      'To calculate:',
      '  - Runway (months) = Cash Balance / Monthly Burn Rate',
      'Factors affecting runway:',
      '  - Revenue growth',
      '  - Cost optimization',
      '  - Fundraising timeline',
      '  - Market conditions'
    ]
  },
  'gross margin': {
    summary: 'Gross margin is the revenue remaining after deducting the direct costs of producing goods or services.',
    category: 'finance',
    synonyms: ['gross profit margin', 'gross profit percentage'],
    relatedTerms: ['profit margin', 'operating margin', 'cogs'],
    details: [
      'Gross margin is a key indicator of business efficiency',
      'Components:',
      '  - Revenue: Total sales',
      '  - COGS: Direct costs of production',
      '  - Labor: Direct labor costs',
      'To calculate:',
      '  - Gross Margin = (Revenue - COGS) / Revenue × 100',
      'Industry variations:',
      '  - Software: 70-80%',
      '  - Retail: 25-35%',
      '  - Manufacturing: 20-35%',
      'Used to:',
      '  - Compare business efficiency',
      '  - Price products',
      '  - Make outsourcing decisions'
    ]
  },
  'kpi': {
    summary: 'Key Performance Indicators (KPIs) are measurable values that demonstrate how effectively a company is achieving key business objectives.',
    category: 'metrics',
    synonyms: ['key performance indicators', 'performance metrics', 'business metrics'],
    relatedTerms: ['metrics', 'performance management', 'balanced scorecard'],
    details: [
      'Types of KPIs:',
      '  - Financial',
      '    * Revenue growth',
      '    * Profit margins',
      '    * Cash flow',
      '  - Customer',
      '    * Satisfaction score',
      '    * Retention rate',
      '    * Acquisition cost',
      '  - Process',
      '    * Efficiency metrics',
      '    * Quality measures',
      '    * Cycle time',
      '  - People',
      '    * Employee satisfaction',
      '    * Turnover rate',
      '    * Productivity',
      'Characteristics of good KPIs:',
      '  - Specific and measurable',
      '  - Achievable and relevant',
      '  - Time-bound',
      '  - Aligned with objectives'
    ]
  },
  'cash flow': {
    summary: 'Cash Flow represents the net amount of cash moving into and out of a business.',
    category: 'finance',
    synonyms: ['cash movement', 'money flow', 'liquidity'],
    relatedTerms: ['working capital', 'liquidity ratio', 'cash management'],
    details: [
      'Types of Cash Flow:',
      '  - Operating Activities',
      '    * Revenue from sales',
      '    * Payments to suppliers',
      '    * Employee salaries',
      '  - Investing Activities',
      '    * Asset purchases',
      '    * Investment in securities',
      '    * Sale of assets',
      '  - Financing Activities',
      '    * Debt payments',
      '    * Dividend payments',
      '    * Stock issuance',
      'Key Metrics:',
      '  - Free Cash Flow',
      '  - Operating Cash Flow Ratio',
      '  - Cash Conversion Cycle',
      'Importance:',
      '  - Business sustainability',
      '  - Investment decisions',
      '  - Growth planning'
    ]
  },
  'business model canvas': {
    summary: 'The Business Model Canvas is a strategic management template for developing new or documenting existing business models.',
    category: 'strategy',
    synonyms: ['bmc', 'canvas model', 'business framework'],
    relatedTerms: ['lean startup', 'value proposition', 'business planning'],
    details: [
      'Nine Building Blocks:',
      '  - Customer Segments',
      '    * Target markets',
      '    * User personas',
      '  - Value Propositions',
      '    * Products and services',
      '    * Problem solutions',
      '  - Channels',
      '    * Distribution',
      '    * Communication',
      '  - Customer Relationships',
      '    * Acquisition',
      '    * Retention',
      '  - Revenue Streams',
      '    * Pricing models',
      '    * Payment methods',
      '  - Key Resources',
      '    * Physical assets',
      '    * Intellectual property',
      '  - Key Activities',
      '    * Core processes',
      '    * Operations',
      '  - Key Partnerships',
      '    * Suppliers',
      '    * Strategic alliances',
      '  - Cost Structure',
      '    * Fixed costs',
      '    * Variable costs'
    ]
  },
  'lean startup': {
    summary: 'The Lean Startup is a methodology for developing businesses and products through experimentation, iteration, and customer feedback.',
    category: 'innovation',
    synonyms: ['lean method', 'lean methodology'],
    relatedTerms: ['mvp', 'agile development', 'business model canvas'],
    details: [
      'Key Principles:',
      '  - Build-Measure-Learn feedback loop',
      '  - Minimum Viable Product (MVP)',
      '  - Validated Learning',
      '  - Innovation Accounting',
      'Core Concepts:',
      '  - Customer Development',
      '    * Problem interviews',
      '    * Solution interviews',
      '    * Product validation',
      '  - Agile Development',
      '    * Rapid iteration',
      '    * Continuous deployment',
      '    * Split testing',
      '  - Pivot or Persevere',
      '    * Data-driven decisions',
      '    * Market feedback',
      '    * Strategic changes'
    ]
  },
  'scalability': {
    summary: 'Scalability is the ability of a business to grow and handle increased demands without losing performance or quality.',
    category: 'operations',
    synonyms: ['growth capacity', 'expandability'],
    relatedTerms: ['growth strategy', 'operational efficiency', 'business model'],
    details: [
      'Types of Scalability:',
      '  - Vertical Scaling',
      '    * Resource enhancement',
      '    * Capacity increase',
      '  - Horizontal Scaling',
      '    * Market expansion',
      '    * Product diversification',
      'Key Factors:',
      '  - Technology Infrastructure',
      '  - Process Automation',
      '  - Resource Management',
      '  - Market Demand',
      'Challenges:',
      '  - Cost management',
      '  - Quality control',
      '  - Team growth',
      '  - Market competition'
    ]
  },
  'break-even analysis': {
    summary: 'Break-even analysis determines the point at which total costs equal total revenues, resulting in neither profit nor loss.',
    category: 'finance',
    synonyms: ['break-even point', 'cost-volume-profit analysis'],
    relatedTerms: ['fixed costs', 'variable costs', 'profit margin'],
    details: [
      'Components:',
      '  - Fixed Costs',
      '    * Rent',
      '    * Salaries',
      '    * Insurance',
      '  - Variable Costs',
      '    * Materials',
      '    * Direct labor',
      '    * Commissions',
      '  - Sales Price',
      '    * Unit price',
      '    * Revenue per unit',
      'Formula:',
      '  - Break-even Point = Fixed Costs / (Price - Variable Costs)',
      'Uses:',
      '  - Pricing decisions',
      '  - Production planning',
      '  - Investment analysis'
    ]
  },
  'competitive advantage': {
    summary: 'Competitive advantage is what makes a business more successful than its competitors in the market.',
    category: 'strategy',
    synonyms: ['competitive edge', 'market advantage'],
    relatedTerms: ['differentiation', 'cost leadership', 'market positioning'],
    details: [
      'Sources of Advantage:',
      '  - Cost Leadership',
      '    * Economies of scale',
      '    * Efficient processes',
      '    * Resource optimization',
      '  - Differentiation',
      '    * Unique features',
      '    * Brand value',
      '    * Innovation',
      '  - Focus Strategy',
      '    * Niche markets',
      '    * Specialized products',
      '    * Customer segments',
      'Sustainability Factors:',
      '  - Difficult to imitate',
      '  - Durable over time',
      '  - Superior to competition',
      '  - Applicable to multiple situations'
    ]
  },
  'branding': {
    summary: 'Branding is the process of creating a strong, positive perception of a company and its products in the customer\'s mind.',
    category: 'marketing',
    synonyms: ['brand building', 'brand management'],
    relatedTerms: ['brand equity', 'marketing strategy', 'customer perception'],
    details: [
      'Key Elements:',
      '  - Brand Identity',
      '    * Logo and design',
      '    * Voice and tone',
      '    * Values and mission',
      '  - Brand Positioning',
      '    * Target audience',
      '    * Market placement',
      '    * Unique value proposition',
      '  - Brand Experience',
      '    * Customer interactions',
      '    * Product quality',
      '    * Service delivery',
      'Benefits:',
      '  - Customer loyalty',
      '  - Premium pricing',
      '  - Market differentiation',
      '  - Word-of-mouth marketing'
    ]
  },
  'risk management': {
    summary: 'Risk management is the process of identifying, assessing, and controlling threats to an organization\'s capital and earnings.',
    category: 'operations',
    synonyms: ['risk mitigation', 'risk control'],
    relatedTerms: ['compliance', 'internal controls', 'business continuity'],
    details: [
      'Risk Management Process:',
      '  - Risk Identification',
      '    * Market risks',
      '    * Operational risks',
      '    * Financial risks',
      '  - Risk Assessment',
      '    * Probability analysis',
      '    * Impact evaluation',
      '    * Risk prioritization',
      '  - Risk Control',
      '    * Prevention measures',
      '    * Mitigation strategies',
      '    * Contingency plans',
      'Best Practices:',
      '  - Regular monitoring',
      '  - Documentation',
      '  - Stakeholder communication',
      '  - Periodic review'
    ]
  },
  'supply chain management': {
    summary: 'Supply Chain Management (SCM) is the handling of the entire production flow of goods or services from raw materials to delivery of the final product.',
    category: 'operations',
    synonyms: ['supply chain', 'logistics management'],
    relatedTerms: ['logistics', 'inventory management', 'procurement'],
    details: [
      'Key Components:',
      '  - Planning',
      '    * Demand forecasting',
      '    * Resource allocation',
      '  - Sourcing',
      '    * Supplier selection',
      '    * Contract management',
      '  - Manufacturing',
      '    * Production scheduling',
      '    * Quality control',
      '  - Delivery',
      '    * Transportation',
      '    * Warehouse management',
      'Optimization Goals:',
      '  - Cost reduction',
      '  - Speed to market',
      '  - Quality assurance',
      '  - Customer satisfaction'
    ]
  },
  'corporate social responsibility': {
    summary: 'Corporate Social Responsibility (CSR) refers to business practices that benefit society while enhancing company value.',
    category: 'strategy',
    synonyms: ['csr', 'corporate citizenship', 'social responsibility'],
    relatedTerms: ['sustainability', 'ethical business', 'stakeholder management'],
    details: [
      'Key Areas:',
      '  - Environmental Impact',
      '    * Carbon footprint',
      '    * Resource conservation',
      '    * Waste management',
      '  - Social Impact',
      '    * Community development',
      '    * Employee welfare',
      '    * Human rights',
      '  - Economic Impact',
      '    * Fair trade',
      '    * Local sourcing',
      '    * Ethical investing',
      'Benefits:',
      '  - Enhanced reputation',
      '  - Employee satisfaction',
      '  - Customer loyalty',
      '  - Risk reduction'
    ]
  },
  'disruptive innovation': {
    summary: 'Disruptive Innovation describes a process where a product or service initially takes root in simple applications at the bottom of a market and then relentlessly moves up market.',
    category: 'innovation',
    synonyms: ['market disruption', 'innovative disruption'],
    relatedTerms: ['innovation strategy', 'technological change', 'market transformation'],
    details: [
      'Characteristics:',
      '  - Initially Inferior',
      '    * Lower performance',
      '    * Cheaper alternatives',
      '    * Simpler features',
      '  - Market Entry',
      '    * New market segments',
      '    * Underserved customers',
      '    * Lower price points',
      '  - Evolution',
      '    * Performance improvement',
      '    * Market expansion',
      '    * Industry transformation',
      'Examples:',
      '  - Personal computers',
      '  - Smartphones',
      '  - Online streaming',
      '  - Electric vehicles'
    ]
  },
  'organizational culture': {
    summary: 'Organizational culture encompasses the values, behaviors, and practices that characterize the working environment.',
    category: 'operations',
    synonyms: ['corporate culture', 'company culture'],
    relatedTerms: ['employee engagement', 'leadership', 'workplace environment'],
    details: [
      'Components:',
      '  - Values and Beliefs',
      '    * Mission statement',
      '    * Core principles',
      '    * Ethics',
      '  - Practices',
      '    * Communication styles',
      '    * Decision-making processes',
      '    * Work habits',
      '  - Physical Environment',
      '    * Office layout',
      '    * Dress code',
      '    * Facilities',
      'Impact Areas:',
      '  - Employee satisfaction',
      '  - Productivity',
      '  - Innovation',
      '  - Customer service'
    ]
  },
  'market segmentation': {
    summary: 'Market segmentation is the process of dividing a market into distinct groups of buyers who have different needs, characteristics, or behaviors.',
    category: 'marketing',
    synonyms: ['customer segmentation', 'target marketing'],
    relatedTerms: ['customer profiling', 'targeting', 'positioning'],
    details: [
      'Segmentation Bases:',
      '  - Demographic',
      '    * Age and gender',
      '    * Income and education',
      '    * Occupation',
      '  - Geographic',
      '    * Region',
      '    * Urban/rural',
      '    * Climate',
      '  - Psychographic',
      '    * Lifestyle',
      '    * Values',
      '    * Personality',
      '  - Behavioral',
      '    * Usage rate',
      '    * Benefits sought',
      '    * Loyalty status',
      'Benefits:',
      '  - Targeted marketing',
      '  - Efficient resource use',
      '  - Better customer service',
      '  - Competitive advantage'
    ]
  },
  'digital transformation': {
    summary: 'Digital transformation is the integration of digital technology into all areas of a business, fundamentally changing how it operates and delivers value.',
    category: 'innovation',
    synonyms: ['digitalization', 'digital adoption'],
    relatedTerms: ['technology strategy', 'change management', 'innovation'],
    details: [
      'Key Areas:',
      '  - Process Digitization',
      '    * Automation',
      '    * Workflow optimization',
      '    * Data integration',
      '  - Customer Experience',
      '    * Digital channels',
      '    * Personalization',
      '    * Self-service options',
      '  - Business Model',
      '    * New revenue streams',
      '    * Digital products',
      '    * Platform business',
      'Success Factors:',
      '  - Leadership commitment',
      '  - Cultural change',
      '  - Technical expertise',
      '  - Customer focus'
    ]
  },
  'burn rate': {
    category: 'metrics',
    synonyms: ['cash burn', 'spending rate'],
    relatedTerms: ['runway', 'cash flow', 'operating expenses'],
    summary: 'Burn rate is the rate at which a company spends its cash reserves or venture capital to fund overhead before generating positive cash flow from operations.',
    details: [
      'It is measured as the amount of cash spent per month to cover operating expenses.',
      'A higher burn rate means a company is spending more money, which can be concerning without sufficient cash reserves.',
      'There are two main types of burn rates:',
      '  - Gross burn rate: Total monthly operating expenses',
      '  - Net burn rate: Total monthly operating losses (expenses minus revenue)',
      'Burn rate is crucial for startups to:',
      '  - Calculate runway (how long until cash runs out)',
      '  - Plan fundraising timing',
      '  - Make strategic cost-cutting decisions',
      '  - Monitor financial health'
    ]
  },
  'churn rate': {
    category: 'metrics',
    synonyms: ['attrition rate', 'customer churn', 'turnover rate'],
    relatedTerms: ['retention rate', 'customer lifetime value', 'customer satisfaction'],
    summary: 'Churn rate is the percentage of customers or subscribers who stop using a service or cancel their subscription during a given time period.',
    details: [
      'It is a key metric for subscription-based businesses and SaaS companies.',
      'Churn rate is calculated as: (Lost Customers ÷ Total Customers at Start) × 100.',
      'Types of churn include:',
      '  - Customer churn: Loss of customers',
      '  - Revenue churn: Loss of recurring revenue',
      '  - Voluntary churn: Customer actively cancels',
      '  - Involuntary churn: Subscription ends due to payment failure',
      'High churn rates can indicate:',
      '  - Product or service issues',
      '  - Poor customer satisfaction',
      '  - Strong competition',
      '  - Pricing problems'
    ]
  },
  'cac': {
    category: 'metrics',
    synonyms: ['customer acquisition cost', 'cost per acquisition'],
    relatedTerms: ['ltv', 'marketing roi', 'conversion rate'],
    summary: 'Customer Acquisition Cost (CAC) is the total cost of acquiring a new customer, including marketing and sales expenses.',
    details: [
      'CAC is calculated by dividing total acquisition costs by number of new customers.',
      'It includes costs like:',
      '  - Marketing and advertising expenses',
      '  - Sales team salaries and commissions',
      '  - Marketing tools and software',
      '  - Content creation and distribution',
      'Important considerations:',
      '  - Should be lower than customer lifetime value (LTV)',
      '  - Helps determine marketing ROI',
      '  - Key for sustainable growth',
      '  - May vary by customer segment or channel'
    ]
  },
  'ltv': {
    category: 'metrics',
    synonyms: ['customer lifetime value', 'clv', 'lifetime value'],
    relatedTerms: ['cac', 'churn rate', 'customer retention'],
    summary: 'Customer Lifetime Value (LTV or CLV) is the total revenue a business expects to earn from a customer throughout the entire relationship.',
    details: [
      'LTV helps businesses understand the long-term value of customer relationships.',
      'Calculation methods include:',
      '  - Historic LTV: Based on actual past revenue',
      '  - Predictive LTV: Uses data modeling for future value',
      '  - Cohort analysis: Groups customers by acquisition period',
      'Key factors affecting LTV:',
      '  - Purchase frequency',
      '  - Average order value',
      '  - Customer retention rate',
      '  - Profit margins',
      'Used to:',
      '  - Guide customer acquisition spending',
      '  - Identify valuable customer segments',
      '  - Optimize marketing strategies'
    ]
  },
  'roi': {
    category: 'finance',
    synonyms: ['return on investment', 'rate of return', 'return'],
    relatedTerms: ['irr', 'payback period', 'profit margin'],
    summary: 'Return on Investment (ROI) measures the profitability of an investment relative to its cost.',
    details: [
      'ROI is calculated as: ((Return - Investment) ÷ Investment) × 100.',
      'Types of ROI metrics:',
      '  - Financial ROI: Direct monetary returns',
      '  - Marketing ROI: Campaign performance',
      '  - Social ROI: Impact of social media',
      '  - Time ROI: Value of time invested',
      'Important considerations:',
      '  - Time period of measurement',
      '  - Risk factors',
      '  - Opportunity costs',
      '  - Direct vs indirect returns',
      'Used for:',
      '  - Investment decisions',
      '  - Performance evaluation',
      '  - Resource allocation',
      '  - Strategy validation'
    ]
  }
};
